version: '3.1'

services:

  db:
    image: mariadb:10.3
    restart: always
    volumes: 
        - ./datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080